name: copy repo

on:
  push:

jobs:
  copy_repo:
    name: copy-repo
    runs-on: ubuntu-latest
    timeout-minutes: 70
    steps:

        - uses: actions/checkout@v2

        - run: mkdir -p artifact_test

        - run: echo hello > artifact_test/world.txt

        - uses: actions/upload-artifact@v2
          with:
            name: artifact_test
            path: artifact_test/world.txt

        - name: Get current branch
          shell: bash
          run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          id: current_branch

        - name: copy repo
          run: |
            CLONE_DIR=$(mktemp -d)

            eval "$(ssh-agent -s)"
            echo "${{secrets.SSH_PRIVATE_KEY }}" > /tmp/repo_rsa 
            chmod 400 /tmp/repo_rsa
            ssh-add /tmp/repo_rsa
            git config --global user.email "abargiela@gmail.com"
            git config --global user.name "abargiela"

            git clone --single-branch --branch ${{ steps.current_branch.outputs.branch }} "git@github.com:abargiela/test_bors_ng_copy.git" $CLONE_DIR

            cd $CLONE_DIR
            if [ -z "${{ steps.current_branch.outputs.branch }}" ]; then
                git checkout -b ${{ steps.current_branch.outputs.branch }}
            fi

            cd - ; rm -rf  $CLONE_DIR
            rsync -az --delete *  $CLONE_DIR \
                --exclude '.git' \
                --exclude '.github';
            cd $CLONE_DIR

            pwd
            git status
            if git status | grep -q "deleted"; then
                git add -u;
            else
                echo No deleted files;
            fi

            git add .
            if git status | grep -q "nothing to commit"; then
                echo "Everything is up to date ";
            else
                git commit --message "Update from https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
                git push --set-upstream origin ${{ steps.current_branch.outputs.branch }}

                #git commit --message "Update from https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
                #GIT_TRACE=1 git push --set-upstream origin ${{ steps.current_branch.outputs.branch }}
                #-u origin HEAD:${{ steps.current_branch.outputs.branch }}
                #git push "https://x-access-token:$API_TOKEN_GITHUB@github.com/abargiela/test_bors_ng_copy.git" HEAD:${{ steps.current_branch.outputs.branch }}  --follow-tags --force --tags 
            fi


#        - name: Copy repository
#          uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
#          env:
#            API_TOKEN_GITHUB: ${{ secrets.BORS }}
#          with:
#            source_file: '*'
#            destination_repo: 'abargiela/test_bors_ng_copy'
#            destination_folder: '/'
#            user_email: 'abargiela@gmail.com'
#            user_name: 'abargiela'
#            commit_message: 'A custom message for the commit'
#            destination_branch: ${{ steps.current_branch.outputs.branch }}
#            destination_branch_create: ${{ steps.current_branch.outputs.branch }}

