name: copy repo

on:
  push:

jobs:
  copy_repo:
    name: copy-repo
    runs-on: ubuntu-latest
    timeout-minutes: 70
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - run: mkdir -p artifact

        - run: echo hello > artifact/world.txt

        - uses: actions/upload-artifact@v2
          with:
            name: artifact_test
            path: artifact_test/world.txt

        - name: check folder
          run: ls -lahS ../; ls -lahS ../../; ls -lahS artifact_test && cd artifact_test && pwd

        - name: Copy
          uses: andstor/copycat-action@v3
          with:
            personal_token: ${{ secrets.BORS }}
            src_path: /.
            dst_path: /backup2/
            dst_owner: abargiela
            dst_repo_name: test_bors_ng_copy
            src_branch: main
            dst_branch: main
