name: copy repo

on:
  push:

jobs:
  copy_repo:
    name: copy-repo
    runs-on: ubuntu-latest
    timeout-minutes: 70
    steps:

        - uses: actions/checkout@v2

        - run: mkdir -p artifact_test

        - run: echo hello > artifact_test/world.txt
        - run: echo hello2 >> artifact_test/world.txt

        - uses: actions/upload-artifact@v2
          with:
            name: artifact_test
            path: artifact_test/world.txt

        - uses: actions/download-artifact@v2
          with:
            name: artifact_test

        - name: branch
          run: echo ${GITHUB_REF##*/}

        - name: Pushes test file
          uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
          env:
            API_TOKEN_GITHUB: ${{ secrets.BORS }}
          with:
            source_file: '*'
            destination_repo: 'abargiela/test_bors_ng_copy'
            destination_folder: '/i'
            user_email: 'abargiela@gmail.com'
            user_name: 'abargiela'
            commit_message: 'A custom message for the commit'
            destination_branch: ${{ env.GITHUB_BASE_REF }}
            destination_branch_create: ${{ env.GITHUB_BASE_REF }}
