name: copy repo

on:
  push:

jobs:
  copy_repo:
    name: copy-repo
    runs-on: ubuntu-latest
    timeout-minutes: 70
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - run: mkdir -p artifact

        - run: echo hello > artifact/world.txt

        - uses: actions/upload-artifact@v2
          with:
            name: my-artifact
            path: artifact/world.txt

        - name: check folder
          run: ls -lahS artifact && cd artifact && pwd

      - uses: olivr/copybara-action@v1.2.2
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          access_token: ${{ secrets.BORS }}
          sot_repo: git@github.com:abargiela/test_bors.git
          destination_repo: git@github.com:abargiela/test_bors_ng_copy.git
