name: copy repo

on:
  push:

jobs:
  copy_repo:
    name: copy-repo
    runs-on: ubuntu-latest
    timeout-minutes: 70
    steps:

        - uses: actions/checkout@v2

        - run: mkdir -p artifact_test

        - run: echo hello > artifact_test/world.txt

        - uses: actions/upload-artifact@v2
          with:
            name: artifact_test
            path: artifact_test/world.txt

        - name: Get current branch
          shell: bash
          run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          id: current_branch

        - name: copy repo
          shell: bash
          run: |
            # Create a temporary folder to clone the other repo
            CLONE_DIR=$(mktemp -d)
            DST_REPO='abargiela/test_bors_ng_copy.git'
            EMAIL='test@gmail.com'
            USERNAME='test'

            # Set the key to be able to clone the repo
            eval "$(ssh-agent -s)"
            echo "${{secrets.SSH_PRIVATE_KEY }}" > /tmp/repo_rsa
            chmod 400 /tmp/repo_rsa
            ssh-add /tmp/repo_rsa
            git config --global user.email $EMAIL
            git config --global user.name $USERNAME

            # cloning the destination repo
            git clone --single-branch --branch ${{ steps.current_branch.outputs.branch }} "git@github.com:$DST_REPO" $CLONE_DIR

            # Create the current branch in the destination repository
            cd $CLONE_DIR
            if [ -z "${{ steps.current_branch.outputs.branch }}" ]; then
                git checkout -b ${{ steps.current_branch.outputs.branch }}
            fi
            # Cleaning all files on the destination repository
            git rm -r .

            # Copy all files from the src repo to the dst repo
            cd - ;
            rsync -az * .gitignore  $CLONE_DIR \
                --exclude '.git' \
                --exclude '.github' \
                --delete;
            cd $CLONE_DIR

            echo 'aaaaaaaaa'
            git status --porcelain | wc -l 
            echo 'aaaaaaaaa'
            if [ $(git status --porcelain | wc -l) -eq 0 ]; then
                echo "Everything is up to date" && exit 0
            fi
            echo 'bbbbbbb'
            git status --porcelain | wc -l
            echo 'bbbbbbb'
            if [ $(git status --porcelain | wc -l) -gt 0 ]; then
                # Check if any modification occurs and then handle it.
                echo 1
                git add -A;
                echo 2
                git commit --message "Update from https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
                echo 3
                git push -u origin ${{ steps.current_branch.outputs.branch }}
                echo 4
            fi

