name: copy repo

on:
  push:

jobs:
  copy_repo:
    name: copy-repo
    runs-on: ubuntu-latest
    timeout-minutes: 70
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: copy
          run: |
             git clone https://.:${{ secrets.BORS }}@github.com/abargiela/test_bors.git target
             git clone git@github.com:abargiela/test_bors_ng_copy.git tmp_files
             rm -rf tmp_files/*
             copy .* tmp_files/
             git add tmp_files
             git commit -m "Automatic publish from github.com/prject"
             git push target master
