name: copy repo

on:
  push:

jobs:
  copy_repo:
    name: copy-repo
    runs-on: ubuntu-latest
    timeout-minutes: 70
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.BORS }}
          src_path: ./
          dst_path: /
          dst_owner: abargiela
          dst_repo_name: test_bors_ng_copy
          src_branch: main
          dst_branch: main

name: delete branch

on:
    pull_request:
    type: closed

        uses: SvanBoxel/delete-merged-branch@main
            #env:
            #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

