name: copy repo

on:
  push:

jobs:
  copy_repo:
    name: copy-repo
    runs-on: ubuntu-latest
    timeout-minutes: 70
    steps:

        - uses: actions/checkout@v2

        - run: mkdir -p artifact_test

        - run: echo hello > artifact_test/world.txt

        - uses: actions/upload-artifact@v2
          with:
            name: artifact_test
            path: artifact_test/world.txt

        - name: Get current branch
          shell: bash
          run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          id: current_branch

        - name: copy repo
          run: |
            mkdir dst_repo
            git config --global user.email "abargiela@gmail.com"
            git config --global user.name "abargiela"
            git clone --single-branch --branch ${{ steps.current_branch.outputs.branch }} "https://x-access-token:$API_TOKEN_GITHUB@github.com/abargiela/test_bors_ng_copy.git" dst_repo 

            rm -rf dst_repo/*
            cd dst_repo

            if [ -z "${{ steps.current_branch.outputs.branch }}" ]; then
                git checkout -b ${{ steps.current_branch.outputs.branch }}
            fi

            cp -R ../* ../.gitignore .

            git add . 
            git commit -m "Automatic publish from github.com/prject"
            git push -u origin HEAD:${{ steps.current_branch.outputs.branch }}


#        - name: Copy repository
#          uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
#          env:
#            API_TOKEN_GITHUB: ${{ secrets.BORS }}
#          with:
#            source_file: '*'
#            destination_repo: 'abargiela/test_bors_ng_copy'
#            destination_folder: '/'
#            user_email: 'abargiela@gmail.com'
#            user_name: 'abargiela'
#            commit_message: 'A custom message for the commit'
#            destination_branch: ${{ steps.current_branch.outputs.branch }}
#            destination_branch_create: ${{ steps.current_branch.outputs.branch }}

