name: copy repo

on:
  push:

jobs:
  copy_repo:
    name: copy-repo
    runs-on: ubuntu-latest
    timeout-minutes: 70
    steps:

        - uses: actions/checkout@v2

        - run: mkdir -p artifact_test

        - run: echo hello > artifact_test/world.txt

        - uses: actions/upload-artifact@v2
          with:
            name: artifact_test
            path: artifact_test/world.txt

        - name: Get current branch
          shell: bash
          run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          id: current_branch

        - name: copy repo
          run: |
            # Create a temporary folder to clone the other repo
            CLONE_DIR=$(mktemp -d)
            DST_REPO='abargiela/test_bors_ng_copy.git'
            EMAIL='abargiela@gmail.com'
            USERNAME='abargiela'

            # Set the key to be able to clone the repo
            eval "$(ssh-agent -s)"
            echo "${{secrets.SSH_PRIVATE_KEY }}" > /tmp/repo_rsa
            chmod 400 /tmp/repo_rsa
            ssh-add /tmp/repo_rsa
            git config --global user.email $EMAIL
            git config --global user.name $USERNAME

            echo 1
            # cloning the destination repo
            git clone --single-branch --branch ${{ steps.current_branch.outputs.branch }} "git@github.com:$DST_REPO" $CLONE_DIR

            echo 2
            # Create the current branch in the destination repository
            cd $CLONE_DIR
            if [ -z "${{ steps.current_branch.outputs.branch }}" ]; then
                git checkout -b ${{ steps.current_branch.outputs.branch }}
            fi
            # Cleaning all files on the destination repository
            git rm -r .

            echo 3
            # Copy all files from the src repo to the dst repo
            cd - ;
            rsync -az --delete .*  $CLONE_DIR \
                --exclude '.git' \
                --exclude '.github';
            cd $CLONE_DIR

            if git status | grep -q "nothing to commit"; then
                echo "No changes detected" && exit 0;
            fi

            # Check if any modification occurs and then handle it.
            if git status | grep -q "deleted" || git status | grep -q "git add"; then
                git add -A;
                git commit --message "Update from https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
                git push -u origin HEAD:${{ steps.current_branch.outputs.branch }}
            fi
