name: sanity checks

on:
  push:

jobs:
  my_python_job:
    name: "Python"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: python version 
      run: python -V
#    - name: install pyenv
#      run: sudo apt-get install pyenv 
#
#    - name: Create virtualenv for python ${{ matrix.python }}
#      run: pyenv local ${{ matrix.python }} && python3 -mvenv .venv-${{ matrix.python }}

#    - name: Install dependencies
#      run: pip install -r requirements.txt
#    - name: Create virtualenv for python ${{ matrix.python-version }}
#      run: pyenv local ${{ matrix.python }} && python3 -mvenv .venv-${{ matrix.python-version }}
#
#    - name: Install dependencies
#      working-directory: ./xa/python
#      run: pip3 install -r requirements.txt
