name: sanity checks

on:
  push:

jobs:
  my_python_job:
    name: "Python"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.7.5
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install python version
      uses: gabrielfalcao/pyenv-action@v5
      with:
        default: "${{ matrix.python }}"
        command: pip install -U pip


#    - name: Create virtualenv for python ${{ matrix.python-version }}
#      run: pyenv local ${{ matrix.python }} && python3 -mvenv .venv-${{ matrix.python-version }}
#
#    - name: Install dependencies
#      working-directory: ./xa/python
#      run: pip3 install -r requirements.txt
