name: sanity checks

on:
  push:

jobs:
  my_python_job:
    name: "Python"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ${GITHUB_WORKSPACE}/venv-${{ matrix.python-version }}/bin
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${GITHUB_WORKSPACE}/venv-${{ matrix.python-version }}/bin

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create virtualenv for python ${{ matrix.python-version }}
      run: python -m venv venv-${{ matrix.python-version }}

    - name: Install dependencies
      working-directory: ./xa/python
      run: ${GITHUB_WORKSPACE}/venv-${{ matrix.python-version }}/bin/pip3 install -r requirements.txt
