name: number2

on: #workflow_dispatch
  push:

jobs:
  copy_repo:
    name: number2
    runs-on: ubuntu-latest
    timeout-minutes: 70
    steps:

        - name: reuse job 1
          run: ${{ jobs.number1 }}
